# Data Prepper Global Configuration
# This file contains server and metrics configuration

# Server port configuration
server_port: 4900

# SSL configuration (if needed)
ssl: false

# Authentication configuration (if needed)
authentication:
  disabled: true

# Circuit breaker configuration
circuit_breakers:
  heap:
    usage: 95
    check_interval: 5s
    
# Processor shutdown timeout
processor_shutdown_timeout: 30s

# Sink shutdown timeout  
sink_shutdown_timeout: 30s

# Metric registries configuration
metric_registries:
  - "Prometheus"

# Metric tags (optional)
metric_tags:
  service: "data-prepper"
  environment: "production"