log-pipeline:
  source:
    otel_logs_source:
      port: 21892
      ssl: false

  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index: "logs-${serviceName}"
        # 서비스 별로 인덱스 생성 (serviceName 변수 사용)

trace-pipeline:
  source:
    otel_trace_source:
      port: 21890
      ssl: false

  processor:
    - otel_traces:
    
  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index: "otel-v1-apm-span"
        insecure: true

service-map-pipeline:
  workers: 2
  delay: "100"
  source:
    pipeline:
      name: "trace-pipeline"
  processor:
    - service_map:
        # The window duration is the maximum length of time the data prepper stores the most recent trace data to evaluvate service-map relationships. 
        # The default is 3 minutes, this means we can detect relationships between services from spans reported in last 3 minutes.
        # Set higher value if your applications have higher latency. 
        window_duration: 180 
  buffer:
      bounded_blocking:
         # buffer_size is the number of ExportTraceRequest from otel-collector the data prepper should hold in memeory. 
         # We recommend to keep the same buffer_size for all pipelines. 
         # Make sure you configure sufficient heap
         # default value is 512
         buffer_size: 512
         # This is the maximum number of request each worker thread will process within the delay.
         # Default is 8.
         # Make sure buffer_size >= workers * batch_size
         batch_size: 8
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        insecure: true
        index: "otel-v1-apm-service-map"
        index_type: trace-analytics-service-map
        # Change to your credentials
        #username: "admin"
        #password: "admin"
        # Add a certificate file if you are accessing an OpenSearch cluster with a self-signed certificate  
        #cert: /path/to/cert
        # If you are connecting to an Amazon OpenSearch Service domain without
        # Fine-Grained Access Control, enable these settings. Comment out the
        # username and password above.
        #aws_sigv4: true
        #aws_region: us-east-1